### ISSUE TITLE
nearestOfType deprecated?

### ISSUE THREAD

**Issue by niamleeson** [miguelcobain/ember-composability-tools#3]
According to Ember 2.9.1 API documentation, nearestOfType has been deprecated. Should it be changed?

**Comment by miguelcobain** [comment]
This is indeed a problem. However, this is solved by using contextual components. You should yield child components with `parentComponent=this`.

**Comment by niamleeson** [comment]
Here's what my app setup looks like:

```
map-component
    - component.js
    - template.hbs

extended-leaflet-component 
    - component.js
    - (no template)

center-marker
    - component.js
    - template.hbs
```

In `map-component`'s template, I am rendering `extended-leaflet-component` and I only have the `tile-layer` as the only component from `ember-leaflet`. Other than `tile-layer` the only contextual component is a simple Ember component (`center-marker`) that is just a marker image. The marker image just sits in the center of the map all the time so that it works like how Uber's app works.

The `center-marker` is not mixed in with `ChildMixin` nor does it have `parentComponent=this` passed to it.
Triggering change to the center-marker causes `ember-leaflet` to initialize the map again, which of course throws an error because the map already exists. The only fix I have so far is doing the following to the `extended-leaflet-component`:

```
didInsertParent() {
    if(Ember.isNone(this._layer)) {
      this._layer = this.createLayer();
      this._addObservers();
      this._addEventListeners();
      if ( this.get('parentComponent') ) {
        this.addToContainer();
      }
      this.didCreateLayer();
    }
  }
```

Any thoughts on what needs to be done to not have this block of code in the `parentComponent`?

**Comment by miguelcobain** [comment]
In what ember version does that happen?

**Comment by niamleeson** [comment]
Currently, I am using Ember 2.9.0

**Comment by edborden** [comment]
@miguelcobain Can you provide an example of the `parentComponent=this` usage?

**Comment by BennyAlex** [comment]
@miguelcobain Should I always use parentComponent=this? And does it have any other effects? Can you extend the readme to this topic, please?

**Comment by miguelcobain** [comment]
@BennyAlex yes, you should. No other effects, it is a drop-in replacement.
By doing that you're basically overriding a computed property that calls `nearestOfType`.

**Comment by acorncom** [comment]
Double-checked with Robert Jackson about whether this property was deprecated in error and he thought that `nearestOfType` will probably stay deprecated.  I think this issue can probably be closed at this point ...
