### ISSUE TITLE
parentComponent seems to be undefined

### ISSUE THREAD

**Issue by niamleeson** [miguelcobain/ember-composability-tools#4]
If I am correct, `parentComponent` is never set and ember-leaflet tries to re-initialize the base-layer and it fails because it already exists.

**Comment by miguelcobain** [comment]
This probably should be an ember-leaflet issue.

But I think you're right: https://github.com/miguelcobain/ember-leaflet/blob/master/addon/templates/current/leaflet-map.hbs#L2-L10

We need to yield with the correct property name. Can you PR that?

**Comment by niamleeson** [comment]
do you mean that `containerLayer` should be named `parentComponent` instead?

**Comment by miguelcobain** [comment]
Exactly.

**Comment by niamleeson** [comment]
PR is submitted.
