### ISSUE TITLE
possible _didSetup issue

### ISSUE THREAD

**Issue by imagolive** [miguelcobain/ember-composability-tools#44]
I've been fighting this addon for a while and have tracked down my issues to -

In Node.js, should this:

```
registerChild(child) {
    this.children.add(child);

    if (this._didSetup) {
      child.setup();
    }
  }
```
be
```
registerChild(child) {
    this.children.add(child);

    if (!this._didSetup) {
      child.setup();
    }
  }
```

Not sure if the guard is wrong.

**Comment by imagolive** [comment]
I wanted to clone, fix and push a PR, but do not know how to get Ember to use a local addon repo. 

Do you know how to do this?

**Comment by miguelcobain** [comment]
Yes. You try the following steps.

Inside the local addon repo directory:
```bash
npm link
```

Inside the ember app directory:
```bash
npm link ember-composability-tools
```

Then you can run `ember s` in your ember app and the addon should be linked.

**Comment by miguelcobain** [comment]
The guard is correct.
`registerChild` is invoked by the child.


```js
if (this._didSetup) {
  child.setup();
}
```

What this code means is that "we only want to set up the child if the parent was already set up".

Please reopen if you're having issues, or, ideally, PR a failing test.
