### ISSUE TITLE
Upgrade to ember-element-helper 0.6.0

### ISSUE THREAD

**Issue by vihai** [miguelcobain/ember-composability-tools#54]
Hello,

Due to this issue:

https://github.com/embroider-build/embroider/issues/1077

npms including pre-1.0 embroider/macros cause various issue. Please consider updating to ember-element-helper 0.6.0 that itself depends on new embroider packages.

**Comment by miguelcobain** [comment]
Released version `1.1.0` with this update. Thanks for reporting.
