### ISSUE TITLE
didInsertParent hook not called?

### ISSUE THREAD

**Issue by allthesignals** [miguelcobain/ember-composability-tools#56]
```
import { Root } from 'ember-composability-tools';

export default class Card extends Root {
  didInsertParent() {
    console.log('test'); // nothing
  }
}
```

Application: 
```hbs
<Card>
  <Button />
</Card>
```

Am I missing something?

**Comment by miguelcobain** [comment]
The problem is that, by extending `Root`, you're probably overriding its template too.

I would try not extending Root and use Root directly as a component in the Card template.

card component js
```js
import { Component } from '@glimmer/component';

export default class Card extends Component {
  didInsertParent() {
    console.log('test'); // nothing
  }
}
```
card component template
```hbs
<Root @didInsertParent={{this.didInsertParent}} ...attributes>
  {{yield}}
</Root>
```

`Root` will render a `div` by default.

**Comment by jagthedrummer** [comment]
The docs show that you should extend `Root` and `Node` in your components, which seems counter to the advice given here. Is there a full example somewhere that shows how all of the pieces are intended to fit together?

**Comment by miguelcobain** [comment]
@jagthedrummer ember-leaflet addon uses ember-composability-tools. You might find something there.
