### ISSUE TITLE
Dependency remote-promises is obsolete

### ISSUE THREAD

**Issue by VladMoglan-eaton** [miguelcobain/ember-composability-tools#61]
Hello, our last cyber security scan resulted in a high/critical license risk being detected regarding the remote-promises dependency that is used within this project. The dependency is deprecated in favor of [`Promise.withResolvers`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/withResolvers) according to the project's [README](https://github.com/midzdotdev/remote-promises) file.

I can give a hand with replacing this dependency if needed, please let me know.

**Comment by miguelcobain** [comment]
Fixed by https://github.com/miguelcobain/ember-composability-tools/pull/62

Thank you.
